#ifndef MATH_BUILDER_MAIN_H
#define MATH_BUILDER_MAIN_H
#include <iostream>
#include <SFML/Graphics.hpp>
#include "headers/FunctionInputField.h"
#include "headers/Screen.h"
#include <sstream>
#include "headers/CursorCoordinates.h"
#include "headers/CoordinatesNetwork.h"
//#include "headers/Counter.h"
#endif //MATH_BUILDER_MAIN_H
